using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public abstract class PickupItem : MonoBehaviour
{
    [SerializeField] private bool destroyOnPickup = true;
    [SerializeField] private LayerMask canBePickupBy;
    [SerializeField] private AudioClip pickupSound;

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if(canBePickupBy.value == (canBePickupBy.value | (1<<collision.gameObject.layer)))
        {
            OnPickedUp(collision.gameObject);
            if(pickupSound)
            {
                SoundManager.PlayClip(pickupSound);
            }

            if (destroyOnPickup)
            {
                Destroy(gameObject);
            }
        }
    }

    protected abstract void OnPickedUp(GameObject receiver);
}
